### ISSUE TITLE
Terraform in Dublin Region

### ISSUE THREAD

**Issue by marciobarbato** [huaweicloud/terraform-provider-huaweicloud#2957] opened 2023-04-26 12:09 UTC
### Terraform Version

```
Terraform v1.4.5
on linux_amd64

```

### Terraform Configuration Files

```hcl
provider "huaweicloud" {
  alias       = "cfproj01-dublin"
  region      = "eu-west-101"
  access_key  = "##HUAWEIACCESSKEYAPROJ##"
  secret_key  = "##HUAWEIACCESSSECRETAPROJ##"
  domain_name = "##HUAWEIACCOUNT##"
}

resource "huaweicloud_identity_group" "group_admins" {
  provider = huaweicloud.cfproj01-dublin
  name     = "Cloud Huawei PoC Admins"
}

```

### Debug Output

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Get "[https://iam.eu-west-101.myhuaweicloud.eu:443/v3/projects?name=eu-west-101"](https://iam.eu-west-101.myhuaweicloud.eu/v3/projects?name=eu-west-101%22): connection error, retries exhausted. Aborting. Last error was: tls: failed to verify certificate: x509: certificate signed by unknown authority
│ 
│   with provider["registry.terraform.io/huaweicloud/huaweicloud"].cfproj01-dublin,
│   on provider.tf line 30, in provider "huaweicloud":
│   30: provider "huaweicloud" {
│ 
╵
##[error]Error: Terraform Plan failed with exit code: 1

### Expected Behavior

Terraform Plan should run normally

### Actual Behavior

Certificate error while trying to run terraform plan that connects to EU-Dublin region
### Steps to Reproduce

terraform init
terraform plan
### Additional Context

I'm trying to use terraform to create groups in Dublin region, I created a native cloud user for terraform in EU-Dublin region, generated the access key/secret and trying to connect with that.
My account can connect to Dublin region via portal

**Comment by ShiChangkuo** [comment] 2023-05-05 02:05
@marciobarbato can you try to trust the SSL certificate with [insecure](https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs#insecure) = true ?

```hcl
provider "huaweicloud" {
  alias       = "cfproj01-dublin"
  region      = "eu-west-101"
  access_key  = "##HUAWEIACCESSKEYAPROJ##"
  secret_key  = "##HUAWEIACCESSSECRETAPROJ##"
  domain_name = "##HUAWEIACCOUNT##"
  insecure    = true
}
```

**Comment by marciobarbato** [comment] 2023-05-08 09:15
Hi @ShiChangkuo, that did the trick, can you map this for fixing for the next releases ? I don't think that skip SSL validation is a good idea

**Comment by ShiChangkuo** [comment] 2023-05-16 03:23
@marciobarbato I'm afraid that this issue is caused by the cloud service side, you can open a service ticket to HuaweiCloud.

**Comment by ShiChangkuo** [comment] 2023-08-01 08:41
I will close it temporarily, If you have any questions, please reopen it. Thanks.

**Closed as completed by ShiChangkuo** 2023-08-01 08:41 UTC
Labels: waiting-response
