### ISSUE TITLE
Cannot Grant Namespace-Level Permissions to CCE with Terraform

### ISSUE THREAD

**Issue by xshot9011** [huaweicloud/terraform-provider-huaweicloud#1281] opened 2021-07-14 10:28 UTC
I have provision CCE cluster but I cannot grant access to Namespace-Level Permissions using Terraform.

**Comment by ShiChangkuo** [comment] 2021-07-17 07:56
@xshot9011 I can not get the point, can you provide more details or follow the issue template?

**Comment by xshot9011** [comment] 2021-07-18 09:34
I create CCE cluster with Terraform then I login to IAM console for generating kubeconfig.json file. After export KUBECONFIG=...., I cannot list the resource in cluster. So I have to grant the namespace level to my IAM.

Can this be done by terraform ?

**Comment by ShiChangkuo** [comment] 2021-07-21 02:13
@Jason-Zhang9309 please have a look at this when you are free.

**Comment by Jason-Zhang9309** [comment] 2021-07-22 02:05
@xshot9011 
I've tried to reproduce the problem you met.
Here are my steps:
1. create a cce cluster 
2. download the kubect configuration file from the cluster details page (there is a label named as kubectl in this page)
![image](https://user-images.githubusercontent.com/39076699/126580418-8cec0fbe-5cd1-4658-a803-fd73faa1d843.png)

3. name the json file downloaded in step 2 as ~/.kube/config
4. run command `kubectl config use-context external`
5. run command `kubectl get pods --all-namespaces`, and I can see several pods in my cluster
![image](https://user-images.githubusercontent.com/39076699/126580894-fcdfed5d-8bae-43df-8af8-022666d7f9ba.png)


If you can't list the resource in your cluster, the reason could be that you have configed `Permissions Management` in cce.
The user who create the cce cluster should have permissions to all namespaces by default.
If you created a cce cluster with user A, but run kubectl with user B, you may need to grant the namespaces by hand. This step can't be done by terraform because there is no API for it.
![image](https://user-images.githubusercontent.com/39076699/126580969-21c73056-a555-4bbc-87fd-f1e8ba0191cc.png)

**Comment by ShiChangkuo** [comment] 2021-09-01 06:21
I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.

**Closed as completed by ShiChangkuo** 2021-09-01 06:21 UTC
Labels: enhancement, waiting-response
